export const CHECK_USER_STATUS_START = 'CHECK_USER_STATUS_START'
export const CHECK_USER_STATUS_SUCCESS = 'CHECK_USER_STATUS_SUCCESS'
export const CHECK_USER_STATUS_FAILURE = 'CHECK_USER_STATUS_FAILURE'

export const CHECK_HAND_STATUS_START = 'CHECK_HAND_STATUS_START'
export const CHECK_HAND_STATUS_SUCCESS = 'CHECK_HAND_STATUS_SUCCESS'
export const CHECK_HAND_STATUS_FAILURE = 'CHECK_HAND_STATUS_FAILURE'

export const CHECK_GAME_STATUS_START = 'CHECK_GAME_STATUS_START'
export const CHECK_GAME_STATUS_SUCCESS = 'CHECK_GAME_STATUS_SUCCESS'
export const CHECK_GAME_CREATE_SUCCESS = 'CHECK_GAME_CREATE_SUCCESS'
export const CHECK_GAME_STATISTICS_SUCCESS = 'CHECK_GAME_STATISTICS_SUCCESS'
export const CHECK_GAME_CURRENT_SUCCESS = 'CHECK_GAME_CURRENT_SUCCESS'
export const CHECK_GAME_STATUS_FAILURE = 'CHECK_GAME_STATUS_FAILURE'

